### ISSUE TITLE
Herokuへの自動デプロイの設定

### ISSUE THREAD

**Issue by takoikatakotako** [tk1to/mandragora-rails#1]
現在はHerokuに高橋くんしかデプロイすることができない。
プッシュすると自動でherokuにデプロイする仕組みが欲しい。

結構簡単にできるので、時間のあるときにぜひやって見てください！
https://j-hack.gitbooks.io/deploy-meteor-app-to-heroku/content/step4.html

**Comment by kthatoto** [comment]
@O-Junpei 設定しました！自動デプロイはmasterブランチで行います。

**Comment by takoikatakotako** [comment]
お疲れ様です。
今晩、自分で建てたissue２をやってプルリクを出します。
それがmasterにマージされたらherokuにアップされるはずなので、それの結果を見て大丈夫そうならissueを閉じます。

**Comment by kthatoto** [comment]
@O-Junpei 承知しました！
じゃあ自分は今晩issue3やりますね。

**Comment by takoikatakotako** [comment]
issue2のマージありがとうございました。
すいません、このrailsのherokuのurlを教えてください！

**Comment by kthatoto** [comment]
https://mandragora-rails.herokuapp.com/
 です！

**Comment by takoikatakotako** [comment]
確認しました、お疲れ様です！
